[project]
name = "ducklake-demo"
version = "0.1.0"
description = "DuckLake demo with PostgreSQL and MinIO"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.0",
]

[dependency-groups]
dev = [
    "pip>=25.2",
    "pytest>=8.4.2",
    "setuptools>=80.9.0",
]
